
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//    
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime;
using System.Collections.Generic;
using Bridge.Model;
using System.ComponentModel.DataAnnotations;

namespace Bridge.TestConsole
{

	public class Product : AbstractEntity	
	{
		public   string Name { get; set; }

		public   int Price { get; set; }

		public virtual long ProductDetail { get; set; }

	}

	public class ProductDetail : AbstractEntity	
	{
		public   string Type { get; set; }

		public   int MakeYear { get; set; }

		public virtual  Product Product { get; set; }

		public   long ProductId { get; set; }

	}

	public class Customer : AbstractEntity	
	{
		public   string Name { get; set; }

		public   string Type { get; set; }

	}

	public class TestXaml : AbstractEntity	
	{
		public   long Test { get; set; }

		public   long g1 { get; set; }

	}

}
